config/routes.rb
Rails.application.routes.draw do
  # get 'orders/index'
  # get 'orders/show'
  # get 'orders/create'
  # get 'orders/edit'
  # get 'orders/destroy'
  # get 'tables/index'
  # get 'tables/show'
  devise_for :users
  root to: 'pages#home'
  get "/admin", to: 'pages#restaurant_admin'
  get "/profil", to: 'pages#profil'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :meals
    resources :tables
  end

  resources :tables do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, except: [:new, :create] do
    resources :orders, only: [:new, :create, :index]
  end

  resources :customers
  resources :orders, only: [:show, :update, :edit, :destroy, :index]
end

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            <% @restaurants.each do |restaurant| %>
                <div class="card font-size-home-pages">


                        <div class="card-trip">
                          <div class="card-trip-infos">
                            <div>
                              <%= link_to restaurant_path(restaurant) do  %>
                                <img src="<%= restaurant.photo %>" alt="resto" id="photo-resto">
                              <% end %>
                              <h4 class="card-title "><%= link_to restaurant.name, restaurant_path(restaurant), class:"deco"  %></h4>
                              <h5 class="des-gps"><em>"<%= restaurant.description%>"</h5></em>
                              <h5 class="des-gps"> ⦿ <%= link_to restaurant.distance_to(@result.first.coordinates).to_f.round(1), restaurant_path(restaurant) %> km</h6>
                               <div class="row bouton">
                              <p><%= link_to "Menu", restaurant_meals_path(restaurant), class:"btn btn-dark" %></p>

                              <p><%= link_to "Choisissez votre table", restaurant_tables_path(restaurant), class:"btn btn-dark" %></p>
                               </div>
                            </div>
                          </div>
                        </div>

                </div>
            <%end%>
        </div>
    </div>
</div>

app/views/pages/profil.html.erb
<div class="col-12 col-lg-6 text-center">
  <h1>Mise à jour Profil</h1>
  <%= simple_form_for @customer do |f| %>
    <%=f.input :last_name, placeholder: "Nom de Famille" %>
    <%=f.input :first_name, placeholder: "Prénom" %>
    <%=f.input :address, placeholder: "Adresse" %>
    <%=f.input :date_of_birth,
                  start_year: Time.now.year - 100,
                  end_year: Time.now.year - 15,
                  order: %i(day month year) %>
    <%=f.button :submit, class:"panier"%>
  <% end %>
</div>