config/routes.rb
Rails.application.routes.draw do
  # get 'orders/index'
  # get 'orders/show'
  # get 'orders/create'
  # get 'orders/edit'
  # get 'orders/destroy'
  # get 'tables/index'
  # get 'tables/show'
  devise_for :users
  root to: 'pages#home'
  get "/admin", to: 'pages#restaurant_admin'
  get "/profil", to: 'pages#profil'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :meals
    resources :tables
  end

  resources :tables do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, except: [:new, :create] do
    resources :orders, only: [:new, :create, :index]
  end

  resources :customers
  resources :orders, only: [:show, :update, :edit, :destroy, :index]
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    @skip_footer = true
    @restaurant = Restaurant.find(params[:restaurant_id])
    @tables = Table.where(restaurant: @restaurant).order(:table_number)
    @reservations = Reservation.where(table_id: @tables)
    @customer = Customer.where(user_id: current_user).first
    @reservation = Reservation.where(customer_id: @customer.id).last
    @customers = Customer.all
  end

  def show
    @skip_footer = true
    @restaurant = Restaurant.find(params[:restaurant_id])
    @table = Table.find(params[:id])
    @reservations = Reservation.where(table_id: @table)
    @customer = Customer.where(user_id: current_user).first
    @reservation = Reservation.where(customer_id: @customer.id).last
    @orders = Order.where(table_id: @table)
    prices = []
    @orders.each { |order| prices << order.meal.price }
    @customers = []
    @reservations.each { |reservation| @customers << reservation.customer }
    @total_per_person = 0
    @split = (@table.bill / @customers.length).round(2)
  end

  def update
    @table = Table.find(params[:id])
    @customer = Customer.where(user_id: current_user).first
    @reservation = Reservation.where(customer_id: @customer.id).last
    if !@order.nil?
      Order.where(reservation_id: @reservation.id).destroy_all
    end
    if !@reservation.nil?
      @reservation.destroy
    end
    split = @table.bill - params[:split_bill].to_f
    @table.bill.zero? if split.zero?
    @table.update(paid: true, booked: false, bill: split)
    redirect_to root_path, alert: "Paiement validé, merci de votre visite"
  end

end

app/views/tables/index.html.erb
<h1 class="text-center"><%= @restaurant.name %></h1>
<div class="row d-flex">
  <% @tables.each do |table| %>
    <p><% @reservations.each do |reservation| %>
      <% if reservation.table_id == table.id %>
         <img src="<%= reservation.customer.avatar%>" class="avatar-sm">
      <% end %>
    <% end %>
    </p>
  <div class="col">
    <div class="card" style="width: 12rem;">
      <div class="card-body table">
      <img src="https://maisondescourtines.com/assets/chair.svg" alt="">
        <h5 class="card-title title">Table <%=table.table_number%></h5>
        <p class="card-text">
        </p>
        <div class="resa">
        <a class="card-title"><%= link_to "Réserver", table_reservations_path(table), method: :post, remote: true%></a>
        </div>
      </div>
    </div>
  </div>
  <% end %>
<div class="container">
    <a class="fixed-bottom panier text-center" href="/">ACCEUIL</a>
  </div>
</div>

app/views/tables/show.html.erb
<div class="col-12 col-lg-6 text-center">
  <div class="card table-show">
    <h1>Table N°<%= @table.table_number %></h1>

    <div class="d-flex justify-content-around border-top">
      <div class="d-flex flex-column share">
        <% if @table.bill != 0 %>
        <h3 class="d-flex flex-row justify-content-between">Total: <p><%= @table.bill %>€</p></h3>
        <%= link_to '💎 Payer 💎', restaurant_table_path(@restaurant, @table, split_bill: @table.bill), method: :patch, class:"btn btn-dark pay" %>
        <% else %>
        <h2> Votre addition a déjà été réglée</h2>
        <%= link_to 'Cloturez la réservation', restaurant_table_path(@restaurant, @table, split_bill: @table.bill), method: :patch, class:"btn btn-dark pay" %>
        <% end %>
      </div>
    </div>

    <div class="d-flex justify-content-around border-top">
      <div class="d-flex flex-column share">
        <% @customers.each do |customer| %>
          <% customer.reservation.orders.each do |order|%>
            <% @total_per_person += order.meal.price %>
          <% end %>
          <% if customer.id == @reservation.customer_id && @total_per_person < @table.bill %>
            <h3 class="d-flex flex-row justify-content-between">Ma commande: <p><%= @total_per_person %>€</p></h3>
            <%= link_to '🧘🏻 Payer 🧘🏻', restaurant_table_path(@restaurant, @table, split_bill: @total_per_person), method: :patch, class:"btn btn-dark pay" %>
          <% end %>
          <% @total_per_person = 0 %>
        <% end %>
      </div>
    </div>

    <div class="d-flex justify-content-around border-top">
      <div class="d-flex flex-column share">
        <% if @customers.length > 1 %>
          <h3 class="d-flex flex-row justify-content-between">Partager: <p><%= @split %>€</p></h3>
          <%= link_to '⚖️ Payer ⚖️', restaurant_table_path(@restaurant, @table, split_bill: @split), method: :patch, class:"btn btn-dark pay" %>
        <% end %>
      </div>
    </div>

    <div class="d-flex justify-content-around border-top">
      <div class="d-flex flex-column share">
        <h3 class="d-flex flex-row justify-content-center">👇🏻 Détails Commande 👇🏻</p></h3>
        <% if @table.bill != 0 %>
          <% @customers.each do |customer| %>
            <%= customer.first_name.capitalize %>
            <% @orders.each do |order| %>
              <% if order.reservation.customer == customer %>
                <p> <%= order.meal.meal_name %> -
                <%= order.meal.price %>€ -</p>
              <%end%>
            <%end%>
          <%end%>
        <%end%>
      </div>
    </div>

  </div>
  <div class="container">
    <a class="fixed-bottom panier" href="/restaurants/<%=@restaurant.id%>/meals">RETOUR AU MENU</a>
  </div>
</div>